// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import * as bootstrap from "bootstrap"

import HelloController from "./hello_controller"
application.register("hello", HelloController)


document.addEventListener('turbo:load', () => {
  let toastEl = document.querySelector('.toast');

  if ( !toastEl ) return;
  var toast = new bootstrap.Toast(toastEl);
  toast.show();
});
